name: CI - Test Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  BuildLinux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo ./install-deps.sh

      - name: Test build module (linux-x64)
        run: npm i && file bin/linux-x64/capnp.node

      # See https://github.com/electron/electron/issues/42510
      - name: Configure electron SUID sandbox helper
        run: |
          sudo chown root: ./node_modules/electron/dist/chrome-sandbox
          sudo chmod 4755 ./node_modules/electron/dist/chrome-sandbox

      - name: Run tests
        run: npm test

# vim: set nospell:
